apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: batch-job-every-5-minutes
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: periodic-batch-job
        spec:
          restartPolicy: OnFailure
          containers:
          - image: 011092295y/batch-job
            name: main
