apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kubia-rc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - image: 011092295y/kubia
        name: kubia
        ports:
        - containerPort: 8080
