apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kubia-rs-expressive
spec:
  replicas: 3
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - kubia
      - darkside
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - image: 011092295y/kubia
        name: kubia
        ports:
        - containerPort: 8080
